Repository cisco/mindmeld, pull requests merged in 2019-09, with the labels that each got.

#57 Fixed bug in UI
  mindmeld-ui/src/app/components/resolved-entity-tag-component.jsx
Labels: 4.2

#49 Update WebexBotServer's API and update doc
  mindmeld/bot/webex_bot_server.py
  source/integrations/webex_teams.rst
Labels: doc, enhancement

#56 Adding Converter cli
  mindmeld/cli.py
  mindmeld/components/nlp.py
  mindmeld/converter/__init__.py
  mindmeld/converter/dialogflow.py
  mindmeld/converter/rasa.py
  tests/components/test_question_answerer.py
  tests/converter/dialogflow.py
Labels: 4.2

#61 Enabled locale and language support for system entity resolution
  mindmeld/app_manager.py
  mindmeld/components/classifier.py
  mindmeld/components/nlp.py
  mindmeld/components/request.py
  mindmeld/core.py
  mindmeld/query_factory.py
  mindmeld/ser.py
  setup.py
  tests/components/test_dialogue.py
Labels: 4.2

#62 Added stemmers module to the platform
  mindmeld/components/nlp.py
  mindmeld/components/request.py
  mindmeld/query_factory.py
  mindmeld/ser.py
  mindmeld/stemmers.py
  tests/conftest.py
Labels: 4.2

#24 Implement DialogueManager.reprocess(...)
  mindmeld/components/dialogue.py
  source/userguide/dm.rst
  tests/components/test_dialogue_flow.py
  tests/kwik_e_mart/__init__.py
  tests/kwik_e_mart/app_async.py
Labels: 4.2, enhancement

#59 Update history and change list
  source/index.rst
  source/integrations/converters.rst
  source/userguide/dm.rst
  source/userguide/kb.rst
  source/versions/changes.rst
  source/versions/history.rst
Labels: 4.2
