Repository cisco/mindmeld, pull requests merged in 2019-05, with the labels that each got.

#1 Remove previous params
  mindmeld/app_manager.py
  mindmeld/components/request.py
  source/quickstart/10_deploy_to_production.rst
  source/userguide/dm.rst
  tests/components/test_dialogue.py
  tests/components/test_dialogue_async.py
  tests/kwik_e_mart/__init__.py
  tests/kwik_e_mart/app_async.py
Labels: bug

#3 Question answerer to fetch variable number of records
  docker/conf/pip.conf
  mindmeld/cli.py
  mindmeld/components/question_answerer.py
Labels: enhancement

#4 Small update for duckling and docker
  docker/Dockerfile
  docker/conf/config.cfg
  docker/conf/elasticsearch.yml
  mindmeld/cli.py
  source/userguide/getting_started.rst
Labels: enhancement

#7 Update build process
  source/_static/favicon.ico
  source/_templates/layout.html
  source/blueprints/food_ordering.rst
  source/conf.py
  source/index.rst
  source/quickstart/10_deploy_to_production.rst
  source/userguide/getting_started.rst
Labels: doc

#6 Update documentation for the QuestionAnswerer API
  source/userguide/kb.rst
Labels: doc
